steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/d20:base || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', 'd20:base',
    '-t', 'gcr.io/$PROJECT_ID/d20:base',
    '--cache-from', 'gcr.io/$PROJECT_ID/d20:base',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/d20:base']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/d20:latest',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/coverage.Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/d20:coverage',
    '.'
  ]
images: ['gcr.io/$PROJECT_ID/d20:base', 'gcr.io/$PROJECT_ID/d20:latest', 'gcr.io/$PROJECT_ID/d20:coverage']
